package view;

import dataAccess.DatabaseConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author madsh
 */
public class Login extends javax.swing.JFrame {
    
    public Login() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        bioTrioLabel = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        quitPanel = new javax.swing.JPanel();
        quitButton = new javax.swing.JButton();
        eastPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        hostPanel = new javax.swing.JPanel();
        hostLabel = new javax.swing.JLabel();
        hostTextPanel = new javax.swing.JPanel();
        hostText = new javax.swing.JTextField();
        portPanel = new javax.swing.JPanel();
        portLabel = new javax.swing.JLabel();
        portTextPanel = new javax.swing.JPanel();
        portText = new javax.swing.JTextField();
        dbPanel = new javax.swing.JPanel();
        dbLabel = new javax.swing.JLabel();
        dbTextPanel = new javax.swing.JPanel();
        dbText = new javax.swing.JTextField();
        userPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        userTextPanel = new javax.swing.JPanel();
        userText = new javax.swing.JTextField();
        pwPanel = new javax.swing.JPanel();
        pwLabel = new javax.swing.JLabel();
        pwTextPanel = new javax.swing.JPanel();
        pwField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("loginFrame"); // NOI18N

        northPanel.setMinimumSize(new java.awt.Dimension(800, 100));
        northPanel.setPreferredSize(new java.awt.Dimension(800, 100));

        bioTrioLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bioTrioLabel.setText("Bio Trio Access");
        northPanel.add(bioTrioLabel);

        getContentPane().add(northPanel, java.awt.BorderLayout.NORTH);

        southPanel.setPreferredSize(new java.awt.Dimension(800, 100));

        loginPanel.setPreferredSize(new java.awt.Dimension(150, 50));

        loginButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.setPreferredSize(new java.awt.Dimension(80, 30));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton);

        southPanel.add(loginPanel);

        quitPanel.setPreferredSize(new java.awt.Dimension(150, 50));

        quitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quitButton.setText("Quit");
        quitButton.setPreferredSize(new java.awt.Dimension(80, 30));
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        quitPanel.add(quitButton);

        southPanel.add(quitPanel);

        getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

        eastPanel.setPreferredSize(new java.awt.Dimension(100, 400));
        getContentPane().add(eastPanel, java.awt.BorderLayout.EAST);

        westPanel.setPreferredSize(new java.awt.Dimension(100, 400));
        getContentPane().add(westPanel, java.awt.BorderLayout.WEST);

        centerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Database Information"));
        centerPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        centerPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        hostPanel.setMinimumSize(new java.awt.Dimension(250, 100));
        hostPanel.setPreferredSize(new java.awt.Dimension(250, 60));

        hostLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        hostLabel.setText("Host:");
        hostPanel.add(hostLabel);

        centerPanel.add(hostPanel);

        hostTextPanel.setMinimumSize(new java.awt.Dimension(250, 100));
        hostTextPanel.setPreferredSize(new java.awt.Dimension(250, 60));

        hostText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hostText.setPreferredSize(new java.awt.Dimension(200, 30));
        hostTextPanel.add(hostText);

        centerPanel.add(hostTextPanel);

        portPanel.setMinimumSize(new java.awt.Dimension(250, 100));
        portPanel.setPreferredSize(new java.awt.Dimension(250, 60));

        portLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        portLabel.setText("Port:");
        portPanel.add(portLabel);

        centerPanel.add(portPanel);

        portTextPanel.setMinimumSize(new java.awt.Dimension(250, 100));
        portTextPanel.setPreferredSize(new java.awt.Dimension(250, 60));

        portText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        portText.setPreferredSize(new java.awt.Dimension(200, 30));
        portTextPanel.add(portText);

        centerPanel.add(portTextPanel);

        dbPanel.setMinimumSize(new java.awt.Dimension(250, 100));
        dbPanel.setPreferredSize(new java.awt.Dimension(250, 60));

        dbLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        dbLabel.setText("Database:");
        dbPanel.add(dbLabel);

        centerPanel.add(dbPanel);

        dbTextPanel.setMinimumSize(new java.awt.Dimension(250, 100));
        dbTextPanel.setPreferredSize(new java.awt.Dimension(250, 60));

        dbText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dbText.setPreferredSize(new java.awt.Dimension(200, 30));
        dbTextPanel.add(dbText);

        centerPanel.add(dbTextPanel);

        userPanel.setMinimumSize(new java.awt.Dimension(250, 100));
        userPanel.setPreferredSize(new java.awt.Dimension(250, 60));

        userLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        userLabel.setText("Username:");
        userPanel.add(userLabel);

        centerPanel.add(userPanel);

        userTextPanel.setMinimumSize(new java.awt.Dimension(250, 100));
        userTextPanel.setPreferredSize(new java.awt.Dimension(250, 60));

        userText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userText.setPreferredSize(new java.awt.Dimension(200, 30));
        userTextPanel.add(userText);

        centerPanel.add(userTextPanel);

        pwPanel.setMinimumSize(new java.awt.Dimension(250, 100));
        pwPanel.setPreferredSize(new java.awt.Dimension(250, 60));

        pwLabel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        pwLabel.setText("Password:");
        pwPanel.add(pwLabel);

        centerPanel.add(pwPanel);

        pwTextPanel.setMinimumSize(new java.awt.Dimension(250, 100));
        pwTextPanel.setPreferredSize(new java.awt.Dimension(250, 60));

        pwField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pwField.setPreferredSize(new java.awt.Dimension(200, 30));
        pwTextPanel.add(pwField);

        centerPanel.add(pwTextPanel);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
//        gets the login information and passes et to the DatabaseConnection instance.
        String host = hostText.getText();
        String port = portText.getText();
        String databaseName = dbText.getText();
        String username = userText.getText();
        String password = new String(pwField.getPassword());
        try {
            if (DatabaseConnection.getInstance().connect(host, port, databaseName, username, password) != null) {
                JOptionPane.showMessageDialog(null, "--ACCESS GRANTED--");
                setVisible(false);
                new MovieSelection().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "--ACCESS DENIED--");
            }
        } catch (NullPointerException ex) {
            System.out.println("--CONNECTION ERROR: NOT FOUND--");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        //event creates and option pane that asks for confirmation - if confirmed, the program will terminate
        if(JOptionPane.showConfirmDialog(null, "Are you sure you want to quit?") == 0){
        System.exit(0);    
        }
    }//GEN-LAST:event_quitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bioTrioLabel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel dbLabel;
    private javax.swing.JPanel dbPanel;
    private javax.swing.JTextField dbText;
    private javax.swing.JPanel dbTextPanel;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JLabel hostLabel;
    private javax.swing.JPanel hostPanel;
    private javax.swing.JTextField hostText;
    private javax.swing.JPanel hostTextPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel northPanel;
    private javax.swing.JLabel portLabel;
    private javax.swing.JPanel portPanel;
    private javax.swing.JTextField portText;
    private javax.swing.JPanel portTextPanel;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JLabel pwLabel;
    private javax.swing.JPanel pwPanel;
    private javax.swing.JPanel pwTextPanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JPanel quitPanel;
    private javax.swing.JPanel southPanel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTextField userText;
    private javax.swing.JPanel userTextPanel;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables
}
