/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author madsh
 */
public class SeatSelection extends javax.swing.JFrame {

    /**
     * Creates new form SeatSelection
     */
    public SeatSelection() {
        initComponents();
    }

    private void createSeats(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        cinemaLabel = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        eastPanel = new javax.swing.JPanel();
        westPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        northPanel.setMaximumSize(new java.awt.Dimension(800, 50));
        northPanel.setMinimumSize(new java.awt.Dimension(800, 50));
        northPanel.setPreferredSize(new java.awt.Dimension(800, 50));

        cinemaLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cinemaLabel.setText("Sal #");
        northPanel.add(cinemaLabel);

        getContentPane().add(northPanel, java.awt.BorderLayout.NORTH);

        southPanel.setMaximumSize(new java.awt.Dimension(800, 50));
        southPanel.setMinimumSize(new java.awt.Dimension(800, 50));
        southPanel.setPreferredSize(new java.awt.Dimension(800, 50));
        getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

        eastPanel.setMaximumSize(new java.awt.Dimension(50, 400));
        eastPanel.setMinimumSize(new java.awt.Dimension(50, 400));
        eastPanel.setPreferredSize(new java.awt.Dimension(50, 400));
        getContentPane().add(eastPanel, java.awt.BorderLayout.EAST);

        westPanel.setMaximumSize(new java.awt.Dimension(50, 400));
        westPanel.setMinimumSize(new java.awt.Dimension(50, 400));
        westPanel.setPreferredSize(new java.awt.Dimension(50, 400));
        getContentPane().add(westPanel, java.awt.BorderLayout.WEST);

        centerPanel.setMaximumSize(new java.awt.Dimension(700, 500));
        centerPanel.setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel cinemaLabel;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JPanel northPanel;
    private javax.swing.JPanel southPanel;
    private javax.swing.JPanel westPanel;
    // End of variables declaration//GEN-END:variables
}
